
export const GET_USER = 'GET_USER';
export const GET_SELECTED_COURSE = 'GET_SELECTED_COURSE';
export const GET_ACTIVE_TAB = 'GET_ACTIVE_TAB';
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const CHANGE_SELECTED_COURSE = 'CHANGE_SELECTED_COURSE';



